# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1008, 697)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_6 = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 15))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 15))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.current_label = QtWidgets.QLabel(self.widget_6)
        self.current_label.setText("")
        self.current_label.setObjectName("current_label")
        self.horizontalLayout_6.addWidget(self.current_label)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.scrollArea = QtWidgets.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollBars = QtWidgets.QWidget()
        self.scrollBars.setGeometry(QtCore.QRect(0, 0, 621, 615))
        self.scrollBars.setObjectName("scrollBars")
        self.scrollArea.setWidget(self.scrollBars)
        self.verticalLayout_2.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1008, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView_2 = QtWidgets.QMenu(self.menuBar)
        self.menuView_2.setObjectName("menuView_2")
        self.menuConfig = QtWidgets.QMenu(self.menuBar)
        self.menuConfig.setObjectName("menuConfig")
        self.menuSave_Data_Config_2 = QtWidgets.QMenu(self.menuBar)
        self.menuSave_Data_Config_2.setObjectName("menuSave_Data_Config_2")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.dock_label = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_label.sizePolicy().hasHeightForWidth())
        self.dock_label.setSizePolicy(sizePolicy)
        self.dock_label.setMinimumSize(QtCore.QSize(70, 89))
        self.dock_label.setMaximumSize(QtCore.QSize(300, 524287))
        self.dock_label.setObjectName("dock_label")
        self.dockLabels = QtWidgets.QWidget()
        self.dockLabels.setObjectName("dockLabels")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockLabels)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelList = QtWidgets.QListWidget(self.dockLabels)
        self.labelList.setMouseTracking(True)
        self.labelList.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.labelList.setObjectName("labelList")
        self.verticalLayout.addWidget(self.labelList)
        self.dock_label.setWidget(self.dockLabels)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_label)
        self.dock_params = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_params.sizePolicy().hasHeightForWidth())
        self.dock_params.setSizePolicy(sizePolicy)
        self.dock_params.setMinimumSize(QtCore.QSize(153, 129))
        self.dock_params.setMaximumSize(QtCore.QSize(300, 524287))
        self.dock_params.setObjectName("dock_params")
        self.dockFiles = QtWidgets.QWidget()
        self.dockFiles.setObjectName("dockFiles")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dockFiles)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.dockFiles)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.cannyKSize = QtWidgets.QSpinBox(self.dockFiles)
        self.cannyKSize.setProperty("value", 7)
        self.cannyKSize.setObjectName("cannyKSize")
        self.gridLayout_2.addWidget(self.cannyKSize, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.dockFiles)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.boxKSize = QtWidgets.QSpinBox(self.dockFiles)
        self.boxKSize.setProperty("value", 20)
        self.boxKSize.setObjectName("boxKSize")
        self.gridLayout_2.addWidget(self.boxKSize, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.dockFiles)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.labelKSize = QtWidgets.QSpinBox(self.dockFiles)
        self.labelKSize.setProperty("value", 3)
        self.labelKSize.setObjectName("labelKSize")
        self.gridLayout_2.addWidget(self.labelKSize, 2, 1, 1, 1)
        self.dock_params.setWidget(self.dockFiles)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_params)
        self.dock_file_list = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_file_list.sizePolicy().hasHeightForWidth())
        self.dock_file_list.setSizePolicy(sizePolicy)
        self.dock_file_list.setMaximumSize(QtCore.QSize(300, 524287))
        self.dock_file_list.setObjectName("dock_file_list")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fileList = QtWidgets.QListWidget(self.dockWidgetContents)
        self.fileList.setObjectName("fileList")
        self.verticalLayout_5.addWidget(self.fileList)
        self.widget_3 = QtWidgets.QWidget(self.dockWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.fileFilter = QtWidgets.QLineEdit(self.widget_3)
        self.fileFilter.setObjectName("fileFilter")
        self.horizontalLayout_2.addWidget(self.fileFilter)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.dock_file_list.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_file_list)
        self.dock_image_editing_operations = QtWidgets.QDockWidget(MainWindow)
        self.dock_image_editing_operations.setMinimumSize(QtCore.QSize(231, 150))
        self.dock_image_editing_operations.setObjectName("dock_image_editing_operations")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.reverse_crop = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.reverse_crop.setObjectName("reverse_crop")
        self.gridLayout.addWidget(self.reverse_crop, 0, 1, 1, 1)
        self.crop = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.crop.setObjectName("crop")
        self.gridLayout.addWidget(self.crop, 0, 0, 1, 1)
        self.eraser_strength = QtWidgets.QSpinBox(self.dockWidgetContents_2)
        self.eraser_strength.setProperty("value", 5)
        self.eraser_strength.setObjectName("eraser_strength")
        self.gridLayout.addWidget(self.eraser_strength, 1, 1, 1, 1)
        self.magic_wand = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.magic_wand.setCheckable(True)
        self.magic_wand.setObjectName("magic_wand")
        self.gridLayout.addWidget(self.magic_wand, 1, 0, 1, 1)
        self.exit_image_editing = QtWidgets.QPushButton(self.dockWidgetContents_2)
        self.exit_image_editing.setObjectName("exit_image_editing")
        self.gridLayout.addWidget(self.exit_image_editing, 2, 0, 1, 2)
        self.dock_image_editing_operations.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_image_editing_operations)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionOpen_Dir.setIcon(icon1)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionOpen_Recent = QtWidgets.QAction(MainWindow)
        self.actionOpen_Recent.setObjectName("actionOpen_Recent")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/save-as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon3)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionSave_Files = QtWidgets.QAction(MainWindow)
        self.actionSave_Files.setObjectName("actionSave_Files")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionAdvanced_Mode = QtWidgets.QAction(MainWindow)
        self.actionAdvanced_Mode.setCheckable(True)
        self.actionAdvanced_Mode.setObjectName("actionAdvanced_Mode")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon4)
        self.actionZoom_In.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon5)
        self.actionZoom_Out.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionFit_Width = QtWidgets.QAction(MainWindow)
        self.actionFit_Width.setObjectName("actionFit_Width")
        self.actionFit_Window = QtWidgets.QAction(MainWindow)
        self.actionFit_Window.setObjectName("actionFit_Window")
        self.actionCreate_Shape = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/objects.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_Shape.setIcon(icon6)
        self.actionCreate_Shape.setObjectName("actionCreate_Shape")
        self.actionNext_Image = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_Image.setIcon(icon7)
        self.actionNext_Image.setObjectName("actionNext_Image")
        self.actionPrev_Image = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrev_Image.setIcon(icon8)
        self.actionPrev_Image.setObjectName("actionPrev_Image")
        self.actionCheck_Label = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icons/done.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCheck_Label.setIcon(icon11)
        self.actionCheck_Label.setObjectName("actionCheck_Label")
        self.actionZoom_Original = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/zoom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Original.setIcon(icon9)
        self.actionZoom_Original.setObjectName("actionZoom_Original")
        self.actionSave_Label_Raw_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Label_Raw_Data.setCheckable(True)
        self.actionSave_Label_Raw_Data.setObjectName("actionSave_Label_Raw_Data")
        self.actionSave_Label_Compress_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Label_Compress_Data.setCheckable(True)
        self.actionSave_Label_Compress_Data.setChecked(False)
        self.actionSave_Label_Compress_Data.setObjectName("actionSave_Label_Compress_Data")
        self.actionSave_Rf_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Rf_Data.setCheckable(True)
        self.actionSave_Rf_Data.setObjectName("actionSave_Rf_Data")
        self.actionDraw_Polygon = QtWidgets.QAction(MainWindow)
        self.actionDraw_Polygon.setCheckable(True)
        self.actionDraw_Polygon.setChecked(False)
        self.actionDraw_Polygon.setObjectName("actionDraw_Polygon")
        self.actionDraw_Ellipse = QtWidgets.QAction(MainWindow)
        self.actionDraw_Ellipse.setCheckable(True)
        self.actionDraw_Ellipse.setChecked(True)
        self.actionDraw_Ellipse.setObjectName("actionDraw_Ellipse")
        self.actionUpdate_Line_Width = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Line_Width.setObjectName("actionUpdate_Line_Width")
        self.actionUpdate_Line_Color = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Line_Color.setObjectName("actionUpdate_Line_Color")
        self.actionDelete_Shape = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete_Shape.setIcon(icon10)
        self.actionDelete_Shape.setObjectName("actionDelete_Shape")
        self.actionDelete_Label = QtWidgets.QAction(MainWindow)
        self.actionDelete_Label.setObjectName("actionDelete_Label")
        self.actionClear_Canvas = QtWidgets.QAction(MainWindow)
        self.actionClear_Canvas.setObjectName("actionClear_Canvas")
        self.actionUpdate_Font_Size = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Font_Size.setObjectName("actionUpdate_Font_Size")
        self.actionShow_Lable_List = QtWidgets.QAction(MainWindow)
        self.actionShow_Lable_List.setCheckable(True)
        self.actionShow_Lable_List.setChecked(True)
        self.actionShow_Lable_List.setObjectName("actionShow_Lable_List")
        self.actionShow_File_List = QtWidgets.QAction(MainWindow)
        self.actionShow_File_List.setCheckable(True)
        self.actionShow_File_List.setChecked(True)
        self.actionShow_File_List.setObjectName("actionShow_File_List")
        self.actionShow_Dilate_Params = QtWidgets.QAction(MainWindow)
        self.actionShow_Dilate_Params.setCheckable(True)
        self.actionShow_Dilate_Params.setObjectName("actionShow_Dilate_Params")
        self.actionCrop = QtWidgets.QAction(MainWindow)
        self.actionCrop.setObjectName("actionCrop")
        self.actionRemove_Background = QtWidgets.QAction(MainWindow)
        self.actionRemove_Background.setCheckable(True)
        self.actionRemove_Background.setObjectName("actionRemove_Background")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setCheckable(True)
        self.action.setObjectName("action")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_Files)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionCreate_Shape)
        self.menuEdit.addAction(self.actionDelete_Shape)
        self.menuEdit.addAction(self.actionDelete_Label)
        self.menuEdit.addAction(self.actionAdvanced_Mode)
        self.menuView_2.addAction(self.actionCheck_Label)
        self.menuView_2.addAction(self.actionPrev_Image)
        self.menuView_2.addAction(self.actionNext_Image)
        self.menuView_2.addAction(self.actionZoom_In)
        self.menuView_2.addAction(self.actionZoom_Out)
        self.menuView_2.addAction(self.actionZoom_Original)
        self.menuView_2.addAction(self.actionFit_Width)
        self.menuView_2.addAction(self.actionFit_Window)
        self.menuView_2.addAction(self.actionClear_Canvas)
        self.menuConfig.addAction(self.actionUpdate_Line_Width)
        self.menuConfig.addAction(self.actionUpdate_Line_Color)
        self.menuConfig.addAction(self.actionUpdate_Font_Size)
        self.menuSave_Data_Config_2.addAction(self.actionSave_Label_Compress_Data)
        self.menuSave_Data_Config_2.addAction(self.actionSave_Rf_Data)
        self.menuView.addAction(self.actionShow_Lable_List)
        self.menuView.addAction(self.actionShow_File_List)
        self.menuView.addAction(self.actionShow_Dilate_Params)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView_2.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuConfig.menuAction())
        self.menuBar.addAction(self.menuSave_Data_Config_2.menuAction())
        self.mainToolBar.addAction(self.actionOpen)
        self.mainToolBar.addAction(self.actionOpen_Dir)
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addAction(self.actionSave_As)
        self.mainToolBar.addAction(self.actionCreate_Shape)
        self.mainToolBar.addAction(self.actionDelete_Shape)
        self.mainToolBar.addAction(self.actionZoom_In)
        self.mainToolBar.addAction(self.actionZoom_Out)
        self.mainToolBar.addAction(self.actionZoom_Original)
        self.mainToolBar.addAction(self.actionNext_Image)
        self.mainToolBar.addAction(self.actionPrev_Image)
        self.mainToolBar.addAction(self.actionCheck_Label)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "current label:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView_2.setTitle(_translate("MainWindow", "Canvas"))
        self.menuConfig.setTitle(_translate("MainWindow", "Global Setting"))
        self.menuSave_Data_Config_2.setTitle(_translate("MainWindow", "Save Data Config"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.dock_label.setAccessibleName(_translate("MainWindow", "Label List"))
        self.dock_label.setWindowTitle(_translate("MainWindow", "Labels"))
        self.dock_params.setWindowTitle(_translate("MainWindow", "Dilate Params"))
        self.label.setText(_translate("MainWindow", "cannykSize"))
        self.label_2.setText(_translate("MainWindow", "boxkSize"))
        self.label_3.setText(_translate("MainWindow", "labelKSize"))
        self.dock_file_list.setWindowTitle(_translate("MainWindow", "File List"))
        self.checkBox.setText(_translate("MainWindow", "Save File Filter"))
        self.dock_image_editing_operations.setWindowTitle(_translate("MainWindow", "Image Editing Operations"))
        self.reverse_crop.setText(_translate("MainWindow", "Reverse Crop"))
        self.crop.setText(_translate("MainWindow", "Crop"))
        self.magic_wand.setText(_translate("MainWindow", "Magic Wand"))
        self.exit_image_editing.setText(_translate("MainWindow", "Exit Image Editing"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionOpen_Dir.setText(_translate("MainWindow", "Open Dir"))
        self.actionOpen_Dir.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionOpen_Recent.setText(_translate("MainWindow", "Open Recent"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionSave_Files.setText(_translate("MainWindow", "Save Files"))
        self.actionSave_Files.setShortcut(_translate("MainWindow", "Ctrl+Alt+S"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionUndo.setText(_translate("MainWindow", "Undo "))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionAdvanced_Mode.setText(_translate("MainWindow", "Advanced Mode"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionFit_Width.setText(_translate("MainWindow", "Fit Width"))
        self.actionFit_Width.setShortcut(_translate("MainWindow", "Ctrl+Shift+F"))
        self.actionFit_Window.setText(_translate("MainWindow", "Fit Window"))
        self.actionFit_Window.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionCreate_Shape.setText(_translate("MainWindow", "Create Shape"))
        self.actionCreate_Shape.setShortcut(_translate("MainWindow", "W"))
        self.actionNext_Image.setText(_translate("MainWindow", "Next Image"))
        self.actionNext_Image.setShortcut(_translate("MainWindow", "Right"))
        self.actionPrev_Image.setText(_translate("MainWindow", "Prev Image"))
        self.actionPrev_Image.setShortcut(_translate("MainWindow", "Left"))
        self.actionCheck_Label.setText(_translate("MainWindow", "Check_Label"))
        self.actionZoom_Original.setText(_translate("MainWindow", "Zoom Original"))
        self.actionSave_Label_Raw_Data.setText(_translate("MainWindow", "Label Raw Data"))
        self.actionSave_Label_Compress_Data.setText(_translate("MainWindow", "Label Compress Data"))
        self.actionSave_Rf_Data.setText(_translate("MainWindow", "Rf Data"))
        self.actionDraw_Polygon.setText(_translate("MainWindow", "Polygon"))
        self.actionDraw_Ellipse.setText(_translate("MainWindow", "Ellipse"))
        self.actionUpdate_Line_Width.setText(_translate("MainWindow", "Update Line Width"))
        self.actionUpdate_Line_Color.setText(_translate("MainWindow", "Update Line Color"))
        self.actionDelete_Shape.setText(_translate("MainWindow", "Delete Shape"))
        self.actionDelete_Shape.setShortcut(_translate("MainWindow", "Del"))
        self.actionDelete_Label.setText(_translate("MainWindow", "Delete Label"))
        self.actionClear_Canvas.setText(_translate("MainWindow", "Clear Canvas"))
        self.actionUpdate_Font_Size.setText(_translate("MainWindow", "Update Font Size"))
        self.actionShow_Lable_List.setText(_translate("MainWindow", "Show Lable List"))
        self.actionShow_File_List.setText(_translate("MainWindow", "Show File List"))
        self.actionShow_Dilate_Params.setText(_translate("MainWindow", "Show Dilate Params"))
        self.actionCrop.setText(_translate("MainWindow", "Crop"))
        self.actionRemove_Background.setText(_translate("MainWindow", "Remove Background"))
        self.action.setText(_translate("MainWindow", "Image Editing"))

