# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 832)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_generate = QtWidgets.QWidget()
        self.tab_generate.setObjectName("tab_generate")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_generate)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_12 = QtWidgets.QWidget(self.tab_generate)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_2.addWidget(self.widget_12)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_generate)
        self.groupBox_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.loadConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.loadConfig.setObjectName("loadConfig")
        self.gridLayout_11.addWidget(self.loadConfig, 1, 0, 1, 1)
        self.delConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.delConfig.setObjectName("delConfig")
        self.gridLayout_11.addWidget(self.delConfig, 3, 0, 1, 1)
        self.configList = ListWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configList.sizePolicy().hasHeightForWidth())
        self.configList.setSizePolicy(sizePolicy)
        self.configList.setMaximumSize(QtCore.QSize(91, 16777215))
        self.configList.setObjectName("configList")
        self.gridLayout_11.addWidget(self.configList, 0, 0, 1, 1)
        self.createConfig = QtWidgets.QPushButton(self.groupBox_6)
        self.createConfig.setObjectName("createConfig")
        self.gridLayout_11.addWidget(self.createConfig, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.widget_9 = QtWidgets.QWidget(self.tab_generate)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_9)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.src_dir = QtWidgets.QWidget(self.groupBox_3)
        self.src_dir.setObjectName("src_dir")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.src_dir)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_19 = QtWidgets.QLabel(self.src_dir)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.seedPath = QtWidgets.QLineEdit(self.src_dir)
        self.seedPath.setObjectName("seedPath")
        self.horizontalLayout_15.addWidget(self.seedPath)
        self.browse_seed_path = QtWidgets.QPushButton(self.src_dir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_seed_path.sizePolicy().hasHeightForWidth())
        self.browse_seed_path.setSizePolicy(sizePolicy)
        self.browse_seed_path.setMinimumSize(QtCore.QSize(10, 10))
        self.browse_seed_path.setMaximumSize(QtCore.QSize(20, 20))
        self.browse_seed_path.setObjectName("browse_seed_path")
        self.horizontalLayout_15.addWidget(self.browse_seed_path)
        self.verticalLayout_2.addWidget(self.src_dir)
        self.seed_status = QtWidgets.QLabel(self.groupBox_3)
        self.seed_status.setObjectName("seed_status")
        self.verticalLayout_2.addWidget(self.seed_status)
        self.itemsListParam = MultiDictPropertyWidget(self.groupBox_3)
        self.itemsListParam.setMinimumSize(QtCore.QSize(500, 500))
        self.itemsListParam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.itemsListParam.setObjectName("itemsListParam")
        self.verticalLayout_2.addWidget(self.itemsListParam)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_stopcondition = QtWidgets.QLabel(self.widget_3)
        self.label_stopcondition.setObjectName("label_stopcondition")
        self.horizontalLayout_3.addWidget(self.label_stopcondition)
        self.stop_condition = QtWidgets.QComboBox(self.widget_3)
        self.stop_condition.setObjectName("stop_condition")
        self.horizontalLayout_3.addWidget(self.stop_condition)
        self.label_33 = QtWidgets.QLabel(self.widget_3)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_3.addWidget(self.label_33)
        self.generate_num = SpinBoxWidget(self.widget_3)
        self.generate_num.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.generate_num.setMaximum(9999999)
        self.generate_num.setSingleStep(1000)
        self.generate_num.setProperty("value", 0)
        self.generate_num.setObjectName("generate_num")
        self.horizontalLayout_3.addWidget(self.generate_num)
        self.widget_13 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.logging_label = QtWidgets.QLabel(self.widget_13)
        self.logging_label.setText("logging:    ")
        self.horizontalLayout_13.addWidget(self.logging_label)
        self.logging_option = QtWidgets.QComboBox(self.widget_13)
        self.logging_option.setObjectName("logging_option")
        self.logging_option.addItems(['NOTSET','DEBUG','INFO','WARNING','ERROR','CRITICAL'])
        self.logging_option.setCurrentIndex(3)
        self.horizontalLayout_13.addWidget(self.logging_option)
        spacerItem_1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addSpacerItem(spacerItem_1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_2.addWidget(self.widget_13)
        self.widget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clear_seed_list = QtWidgets.QPushButton(self.widget_5)
        self.clear_seed_list.setObjectName("clear_seed_list")
        self.horizontalLayout_4.addWidget(self.clear_seed_list)
        self.verticalLayout_2.addWidget(self.widget_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_9)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.attachmentList = MultiDictPropertyWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attachmentList.sizePolicy().hasHeightForWidth())
        self.attachmentList.setSizePolicy(sizePolicy)
        self.attachmentList.setMinimumSize(QtCore.QSize(0, 100))
        self.attachmentList.setObjectName("attachmentList")
        self.gridLayout_2.addWidget(self.attachmentList, 2, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.groupBox)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.attachment_path = QtWidgets.QLineEdit(self.widget_6)
        self.attachment_path.setObjectName("attachment_path")
        self.horizontalLayout_5.addWidget(self.attachment_path)
        self.browse_attach_path = QtWidgets.QPushButton(self.widget_6)
        self.browse_attach_path.setMinimumSize(QtCore.QSize(20, 0))
        self.browse_attach_path.setMaximumSize(QtCore.QSize(20, 16777215))
        self.browse_attach_path.setObjectName("browse_attach_path")
        self.horizontalLayout_5.addWidget(self.browse_attach_path)
        self.gridLayout_2.addWidget(self.widget_6, 0, 0, 1, 1)
        self.clear_attach_list = QtWidgets.QPushButton(self.groupBox)
        self.clear_attach_list.setObjectName("clear_attach_list")
        self.gridLayout_2.addWidget(self.clear_attach_list, 3, 0, 1, 1)
        self.attach_status = QtWidgets.QLabel(self.groupBox)
        self.attach_status.setObjectName("attach_status")
        self.gridLayout_2.addWidget(self.attach_status, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.generate_algo = QtWidgets.QGroupBox(self.widget_4)
        self.generate_algo.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generate_algo.sizePolicy().hasHeightForWidth())
        self.generate_algo.setSizePolicy(sizePolicy)
        self.generate_algo.setMinimumSize(QtCore.QSize(0, 300))
        self.generate_algo.setObjectName("generate_algo")
        self.gridLayout = QtWidgets.QGridLayout(self.generate_algo)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.property_widget = DictPropertyListTableWidget(self.generate_algo)
        self.property_widget.setMinimumSize(QtCore.QSize(240, 0))
        self.property_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.property_widget.setObjectName("property_widget")
        self.gridLayout.addWidget(self.property_widget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.generate_algo)
        self.groupBox_10 = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dest_dir = QtWidgets.QWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dest_dir.sizePolicy().hasHeightForWidth())
        self.dest_dir.setSizePolicy(sizePolicy)
        self.dest_dir.setObjectName("dest_dir")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.dest_dir)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_18 = QtWidgets.QLabel(self.dest_dir)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_14.addWidget(self.label_18)
        self.destPath = QtWidgets.QLineEdit(self.dest_dir)
        self.destPath.setObjectName("destPath")
        self.horizontalLayout_14.addWidget(self.destPath)
        self.browse_target_dir = QtWidgets.QPushButton(self.dest_dir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_target_dir.sizePolicy().hasHeightForWidth())
        self.browse_target_dir.setSizePolicy(sizePolicy)
        self.browse_target_dir.setMinimumSize(QtCore.QSize(10, 10))
        self.browse_target_dir.setMaximumSize(QtCore.QSize(20, 20))
        self.browse_target_dir.setObjectName("browse_target_dir")
        self.horizontalLayout_14.addWidget(self.browse_target_dir)
        self.verticalLayout_3.addWidget(self.dest_dir)
        self.preview = QtWidgets.QPushButton(self.groupBox_10)
        self.preview.setObjectName("preview")
        self.verticalLayout_3.addWidget(self.preview)
        self.randomGenerate = QtWidgets.QPushButton(self.groupBox_10)
        self.randomGenerate.setObjectName("randomGenerate")
        self.verticalLayout_3.addWidget(self.randomGenerate)
        self.randomGenerate_train = QtWidgets.QPushButton(self.groupBox_10)
        self.randomGenerate_train.setObjectName("randomGenerate_train")
        self.verticalLayout_3.addWidget(self.randomGenerate_train)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.horizontalLayout.addWidget(self.widget_4)
        self.horizontalLayout_2.addWidget(self.widget_9)
        self.tabWidget_2.addTab(self.tab_generate, "")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_train)
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.widget = TrainAndPredictWidget(self.tab_train)
        self.widget.setObjectName("widget")
        self.gridLayout_12.addWidget(self.widget, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_train, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 922, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuasdf = QtWidgets.QMenu(self.menuBar)
        self.menuasdf.setObjectName("menuasdf")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionStart_DLServer = QtWidgets.QAction(MainWindow)
        self.actionStart_DLServer.setCheckable(True)
        self.actionStart_DLServer.setObjectName("actionStart_DLServer")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionSingle_Process = QtWidgets.QAction(MainWindow)
        self.actionSingle_Process.setCheckable(True)
        self.actionSingle_Process.setVisible(True)
        self.actionSingle_Process.setObjectName("actionSingle_Process")
        self.actionRegression_Test = QtWidgets.QAction(MainWindow)
        self.actionRegression_Test.setCheckable(True)
        self.actionRegression_Test.setVisible(True)
        self.actionRegression_Test.setObjectName("actionRegression_Test")
        self.menuasdf.addAction(self.actionSave)
        self.menuasdf.addAction(self.actionSave_As)
        self.menuasdf.addSeparator()
        self.menuTools.addAction(self.actionSingle_Process)
        self.menuTools.addAction(self.actionRegression_Test)
        self.menuBar.addAction(self.menuasdf.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addAction(self.actionSave_As)
        self.mainToolBar.addAction(self.actionStart_DLServer)
        self.mainToolBar.addAction(self.actionSingle_Process)
        self.mainToolBar.addAction(self.actionRegression_Test)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.configList, self.loadConfig)
        MainWindow.setTabOrder(self.loadConfig, self.delConfig)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2D data Generator"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Config List"))
        self.loadConfig.setToolTip(_translate("MainWindow", "load config json file"))
        self.loadConfig.setText(_translate("MainWindow", "Load"))
        self.delConfig.setToolTip(_translate("MainWindow", "delete exist config in list"))
        self.delConfig.setText(_translate("MainWindow", "Delete"))
        self.createConfig.setToolTip(_translate("MainWindow", "create new config copy from selected config row"))
        self.createConfig.setText(_translate("MainWindow", "New"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Seed List"))
        self.label_19.setText(_translate("MainWindow", "Seed Dir:"))
        self.seedPath.setText(_translate("MainWindow", "D:\\data\\2d generate"))
        self.browse_seed_path.setText(_translate("MainWindow", "..."))
        self.label_stopcondition.setText(_translate("MainWindow", "Stop Condition"))
        self.label_33.setText(_translate("MainWindow", "Generate Num"))
        self.clear_seed_list.setText(_translate("MainWindow", "Clear Selected Seeds"))
        self.groupBox.setTitle(_translate("MainWindow", "Attachment List (only PNG files are valid attachments)"))
        self.label.setText(_translate("MainWindow", "Attach Dir"))
        self.browse_attach_path.setText(_translate("MainWindow", "..."))
        self.clear_attach_list.setText(_translate("MainWindow", "Clear Attachment List"))
        self.generate_algo.setTitle(_translate("MainWindow", "Generate Algorithm"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Start Generate"))
        self.label_18.setText(_translate("MainWindow", "Target Dir:"))
        self.destPath.setText(_translate("MainWindow", "D:\\data\\2d generate-result"))
        self.browse_target_dir.setText(_translate("MainWindow", "..."))
        self.preview.setText(_translate("MainWindow", "Preview"))
        self.randomGenerate.setText(_translate("MainWindow", "Generate"))
        self.randomGenerate_train.setText(_translate("MainWindow", "generate and train"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_generate), _translate("MainWindow", "Generate Data"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_train), _translate("MainWindow", " Train and Predict"))
        self.menuasdf.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionStart_DLServer.setText(_translate("MainWindow", "Start DLServer"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save in target dir"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionSingle_Process.setText(_translate("MainWindow", "Single_Process"))
        self.actionSingle_Process.setToolTip(_translate("MainWindow", "gnenerate all data in single process manner."))
        self.actionRegression_Test.setText(_translate("MainWindow", "Regression_Test"))
        self.actionRegression_Test.setToolTip(_translate("MainWindow", "gnenerate all data without random."))


from ui.DictPropertyListTableWidget import DictPropertyListTableWidget
from ui.ListWidget import ListWidget
from ui.MultiDictPropertyWidget import MultiDictPropertyWidget
from ui.SpinBoxWidget import SpinBoxWidget
from ui.TrainAndPredictWidget import TrainAndPredictWidget
