# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainAndPredictWidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TrainAndPredictWidget(object):
    def setupUi(self, TrainAndPredictWidget):
        TrainAndPredictWidget.setObjectName("TrainAndPredictWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(TrainAndPredictWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(TrainAndPredictWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Trainning = QtWidgets.QWidget()
        self.Trainning.setObjectName("Trainning")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Trainning)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.check_period = QtWidgets.QSpinBox(self.Trainning)
        self.check_period.setMaximum(2000)
        self.check_period.setProperty("value", 80)
        self.check_period.setObjectName("check_period")
        self.gridLayout_6.addWidget(self.check_period, 3, 1, 1, 2)
        self.start_train = QtWidgets.QPushButton(self.Trainning)
        self.start_train.setObjectName("start_train")
        self.gridLayout_6.addWidget(self.start_train, 4, 0, 1, 2)
        self.widget_6 = QtWidgets.QWidget(self.Trainning)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.widget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.epoches = QtWidgets.QSpinBox(self.widget_6)
        self.epoches.setMaximum(2000)
        self.epoches.setProperty("value", 100)
        self.epoches.setObjectName("epoches")
        self.horizontalLayout_12.addWidget(self.epoches)
        self.gridLayout_6.addWidget(self.widget_6, 2, 0, 1, 3)
        self.label_51 = QtWidgets.QLabel(self.Trainning)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 3, 0, 1, 1)
        self.data_dir = QtWidgets.QWidget(self.Trainning)
        self.data_dir.setObjectName("data_dir")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.data_dir)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.data_dir)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.trainPath = QtWidgets.QLineEdit(self.data_dir)
        self.trainPath.setObjectName("trainPath")
        self.horizontalLayout_10.addWidget(self.trainPath)
        self.browse_train = QtWidgets.QPushButton(self.data_dir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_train.sizePolicy().hasHeightForWidth())
        self.browse_train.setSizePolicy(sizePolicy)
        self.browse_train.setMinimumSize(QtCore.QSize(10, 10))
        self.browse_train.setMaximumSize(QtCore.QSize(20, 20))
        self.browse_train.setObjectName("browse_train")
        self.horizontalLayout_10.addWidget(self.browse_train)
        self.gridLayout_6.addWidget(self.data_dir, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(20, 564, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 5, 0, 1, 3)
        self.data_dir_2 = QtWidgets.QWidget(self.Trainning)
        self.data_dir_2.setObjectName("data_dir_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.data_dir_2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.data_dir_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.weightPath = QtWidgets.QLineEdit(self.data_dir_2)
        self.weightPath.setObjectName("weightPath")
        self.horizontalLayout_11.addWidget(self.weightPath)
        self.browse_weight = QtWidgets.QPushButton(self.data_dir_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_weight.sizePolicy().hasHeightForWidth())
        self.browse_weight.setSizePolicy(sizePolicy)
        self.browse_weight.setMinimumSize(QtCore.QSize(10, 10))
        self.browse_weight.setMaximumSize(QtCore.QSize(20, 20))
        self.browse_weight.setObjectName("browse_weight")
        self.horizontalLayout_11.addWidget(self.browse_weight)
        self.gridLayout_6.addWidget(self.data_dir_2, 1, 0, 1, 3)
        self.tabWidget.addTab(self.Trainning, "")
        self.Predict = QtWidgets.QWidget()
        self.Predict.setObjectName("Predict")
        self.groupBox_2 = QtWidgets.QGroupBox(self.Predict)
        self.groupBox_2.setGeometry(QtCore.QRect(9, 9, 1211, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.predict_dir = QtWidgets.QWidget(self.groupBox_2)
        self.predict_dir.setObjectName("predict_dir")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.predict_dir)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.predict_dir)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.predictPath = QtWidgets.QLineEdit(self.predict_dir)
        self.predictPath.setObjectName("predictPath")
        self.horizontalLayout_7.addWidget(self.predictPath)
        self.browse_predict = QtWidgets.QPushButton(self.predict_dir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_predict.sizePolicy().hasHeightForWidth())
        self.browse_predict.setSizePolicy(sizePolicy)
        self.browse_predict.setMinimumSize(QtCore.QSize(10, 10))
        self.browse_predict.setMaximumSize(QtCore.QSize(20, 20))
        self.browse_predict.setObjectName("browse_predict")
        self.horizontalLayout_7.addWidget(self.browse_predict)
        self.gridLayout_7.addWidget(self.predict_dir, 0, 0, 1, 2)
        self.modeldir = QtWidgets.QWidget(self.groupBox_2)
        self.modeldir.setObjectName("modeldir")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.modeldir)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.modeldir)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.modelPath = QtWidgets.QLineEdit(self.modeldir)
        self.modelPath.setObjectName("modelPath")
        self.horizontalLayout_3.addWidget(self.modelPath)
        self.browse_model = QtWidgets.QPushButton(self.modeldir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_model.sizePolicy().hasHeightForWidth())
        self.browse_model.setSizePolicy(sizePolicy)
        self.browse_model.setMinimumSize(QtCore.QSize(10, 10))
        self.browse_model.setMaximumSize(QtCore.QSize(20, 20))
        self.browse_model.setObjectName("browse_model")
        self.horizontalLayout_3.addWidget(self.browse_model)
        self.gridLayout_7.addWidget(self.modeldir, 1, 0, 1, 2)
        self.save_predict = QtWidgets.QPushButton(self.groupBox_2)
        self.save_predict.setObjectName("save_predict")
        self.gridLayout_7.addWidget(self.save_predict, 2, 0, 1, 2)
        self.calculate_mAP = QtWidgets.QPushButton(self.groupBox_2)
        self.calculate_mAP.setObjectName("calculate_mAP")
        self.gridLayout_7.addWidget(self.calculate_mAP, 3, 0, 1, 1)
        self.mAP = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.mAP.setReadOnly(True)
        self.mAP.setDecimals(5)
        self.mAP.setMaximum(1.0)
        self.mAP.setObjectName("mAP")
        self.gridLayout_7.addWidget(self.mAP, 3, 1, 1, 1)
        self.tabWidget.addTab(self.Predict, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(TrainAndPredictWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TrainAndPredictWidget)

    def retranslateUi(self, TrainAndPredictWidget):
        _translate = QtCore.QCoreApplication.translate
        TrainAndPredictWidget.setWindowTitle(_translate("TrainAndPredictWidget", "Form"))
        self.start_train.setText(_translate("TrainAndPredictWidget", "Start Trainning"))
        self.label_13.setText(_translate("TrainAndPredictWidget", "Epoch Num"))
        self.label_51.setText(_translate("TrainAndPredictWidget", "Check Period"))
        self.label_11.setText(_translate("TrainAndPredictWidget", "Data Dir:"))
        self.browse_train.setText(_translate("TrainAndPredictWidget", "..."))
        self.label_12.setText(_translate("TrainAndPredictWidget", "Weight File:"))
        self.browse_weight.setText(_translate("TrainAndPredictWidget", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Trainning), _translate("TrainAndPredictWidget", "Trainning"))
        self.groupBox_2.setTitle(_translate("TrainAndPredictWidget", "Predict Data"))
        self.label_7.setText(_translate("TrainAndPredictWidget", "Image Dir:"))
        self.browse_predict.setText(_translate("TrainAndPredictWidget", "..."))
        self.label_5.setText(_translate("TrainAndPredictWidget", "Model Dir:"))
        self.browse_model.setText(_translate("TrainAndPredictWidget", "..."))
        self.save_predict.setText(_translate("TrainAndPredictWidget", "Predict and save result to xml"))
        self.calculate_mAP.setText(_translate("TrainAndPredictWidget", "Calculate mAP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Predict), _translate("TrainAndPredictWidget", "Predict"))

